### ISSUE TITLE
/staff.html lacks a mention about an IRC channel to contact network operators

### ISSUE THREAD

**Issue by dolmen** [perl-irc/perl-irc.github.io#4]
Is there a IRC channel where I can find all the network operators (instead of contacting each of them individually)? If yes, it should be mentionned on the [`/staff.html`](http://www.irc.perl.org/staff.html) page.

**Comment by sungo** [comment]
The SRB will contact the network operators if necessary. Please take all issues to #magnet-srb and we'll get things sorted out from there.

**Comment by dolmen** [comment]
So `#magnet-srb` should be mentioned on that page...
